# Stage 1: Build Stage with Node.js
FROM node:slim as builder

WORKDIR /app

COPY --chown=node:node . /app

# Install frontend dependencies and build assets
RUN npm install \
    && npm run build

# Stage 3: Build PHP Application
FROM ghcr.io/ReneDyhr/Kirke-Foto:base as app-builder

WORKDIR /var/www/html/

COPY --chown=www-data:www-data . /var/www/html/
COPY --from=builder /app/public /var/www/html/public

# Install backend dependencies and optimize Laravel
RUN /usr/local/bin/composer install --no-interaction --optimize-autoloader --no-dev

RUN touch laravel.cron && \
    echo "* * * * * cd /var/www/html/ && /usr/local/bin/php artisan schedule:run" >> laravel.cron && \
    crontab laravel.cron

# Stage 4: Production Image
FROM ghcr.io/ReneDyhr/Kirke-Foto:base as production

WORKDIR /var/www/html/

COPY --from=app-builder /var/www/html/ /var/www/html/

COPY docker/production/supervisor.conf /etc/supervisor/conf.d/worker.conf

RUN mkdir /var/www/.npm

RUN chown -R www-data:www-data /var/www/

USER www-data

CMD ["/usr/bin/supervisord", "-c", "/etc/supervisor/conf.d/worker.conf"]
