# Stage 1: Base Image with PHP and Required Extensions
FROM php:8.4-apache

ARG PHP_EXTS="bcmath ctype fileinfo mbstring pdo pdo_mysql intl dom pcntl zip sodium"

RUN apt update \
    && apt install -y libonig-dev libicu-dev libsodium-dev libxml2-dev libzip-dev zip libpng-dev libjpeg-dev libfreetype6-dev libwebp-dev cron curl supervisor \
    && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/* \
    && docker-php-ext-install -j$(nproc) ${PHP_EXTS} \
    && docker-php-ext-configure gd --with-freetype --with-jpeg --with-webp \
    && docker-php-ext-install -j$(nproc) gd \
    && a2enmod rewrite remoteip \
    && apt purge -y --auto-remove libonig-dev libxml2-dev \
    && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*

ENV APACHE_DOCUMENT_ROOT /var/www/html/public

RUN sed -ri -e 's!/var/www/html!${APACHE_DOCUMENT_ROOT}!g' /etc/apache2/sites-available/*.conf
RUN sed -ri -e 's!/var/www/!${APACHE_DOCUMENT_ROOT}!g' /etc/apache2/apache2.conf /etc/apache2/conf-available/*.conf

COPY docker/production/apache-remoteip.conf /etc/apache2/conf-available/remoteip.conf
RUN a2enconf remoteip

# Copy Composer from official Composer image
COPY --from=composer:latest /usr/bin/composer /usr/local/bin/composer

RUN apt update \
    && apt install -y zip unzip git \
    && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*
